-- Migration: Add Indian Castes/Communities Table
-- Created: 2025-11-19

-- Create castes table
CREATE TABLE IF NOT EXISTS `castes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `caste_name` VARCHAR(100) NOT NULL,
  `religion` VARCHAR(50) NOT NULL,
  `category` VARCHAR(50) DEFAULT NULL COMMENT 'General, OBC, SC, ST, etc',
  `region` VARCHAR(100) DEFAULT NULL,
  `status` TINYINT(1) DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_religion` (`religion`),
  KEY `idx_caste_name` (`caste_name`),
  KEY `idx_category` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert Hindu Castes/Communities
INSERT INTO `castes` (`caste_name`, `religion`, `category`, `region`) VALUES
-- Brahmin Castes
('Brahmin', 'Hindu', 'General', 'All India'),
('Iyer', 'Hindu', 'General', 'Tamil Nadu'),
('Iyengar', 'Hindu', 'General', 'Tamil Nadu'),
('Namboodiri', 'Hindu', 'General', 'Kerala'),
('Deshastha Brahmin', 'Hindu', 'General', 'Maharashtra'),
('Chitpavan Brahmin', 'Hindu', 'General', 'Maharashtra'),
('Karhade Brahmin', 'Hindu', 'General', 'Maharashtra'),
('Konkanastha Brahmin', 'Hindu', 'General', 'Maharashtra'),
('Saraswat Brahmin', 'Hindu', 'General', 'Goa, Karnataka'),
('Gaur Brahmin', 'Hindu', 'General', 'North India'),
('Kanyakubj Brahmin', 'Hindu', 'General', 'Uttar Pradesh'),
('Saryuparin Brahmin', 'Hindu', 'General', 'Uttar Pradesh'),
('Bhumihar Brahmin', 'Hindu', 'General', 'Bihar, Uttar Pradesh'),
('Maithil Brahmin', 'Hindu', 'General', 'Bihar, Jharkhand'),
('Bengali Brahmin', 'Hindu', 'General', 'West Bengal'),
('Mohyal Brahmin', 'Hindu', 'General', 'Punjab, Haryana'),
('Kashmiri Pandit', 'Hindu', 'General', 'Jammu & Kashmir'),
('Havyaka Brahmin', 'Hindu', 'General', 'Karnataka'),
('Madhwa Brahmin', 'Hindu', 'General', 'Karnataka'),
('Smartha Brahmin', 'Hindu', 'General', 'South India'),
('Vaidiki Brahmin', 'Hindu', 'General', 'Andhra Pradesh'),
('Niyogi Brahmin', 'Hindu', 'General', 'Andhra Pradesh'),
('Gurukkal Brahmin', 'Hindu', 'General', 'Tamil Nadu'),
('Badaga', 'Hindu', 'General', 'Tamil Nadu'),
('Daivadnya Brahmin', 'Hindu', 'General', 'Goa, Karnataka'),

-- Kshatriya Castes
('Kshatriya', 'Hindu', 'General', 'All India'),
('Rajput', 'Hindu', 'General', 'North India'),
('Maratha', 'Hindu', 'General', 'Maharashtra'),
('96 Kuli Maratha', 'Hindu', 'General', 'Maharashtra'),
('Kunbi', 'Hindu', 'OBC', 'Maharashtra'),
('Reddy', 'Hindu', 'OBC', 'Andhra Pradesh, Telangana'),
('Kamma', 'Hindu', 'OBC', 'Andhra Pradesh, Telangana'),
('Kapu', 'Hindu', 'OBC', 'Andhra Pradesh'),
('Velama', 'Hindu', 'OBC', 'Andhra Pradesh, Telangana'),
('Nair', 'Hindu', 'General', 'Kerala'),
('Menon', 'Hindu', 'General', 'Kerala'),
('Pillai', 'Hindu', 'OBC', 'Tamil Nadu, Kerala'),
('Naidu', 'Hindu', 'OBC', 'Andhra Pradesh, Tamil Nadu'),
('Gowda', 'Hindu', 'OBC', 'Karnataka'),
('Vokkaligas', 'Hindu', 'General', 'Karnataka'),
('Lingayat', 'Hindu', 'OBC', 'Karnataka'),
('Adi Dravidar', 'Hindu', 'SC', 'Tamil Nadu'),
('Thakur', 'Hindu', 'General', 'North India'),
('Chauhan', 'Hindu', 'General', 'Rajasthan'),
('Rathore', 'Hindu', 'General', 'Rajasthan'),
('Sisodiya', 'Hindu', 'General', 'Rajasthan'),
('Gujjar', 'Hindu', 'OBC', 'North India'),
('Jat', 'Hindu', 'OBC', 'North India'),
('Yadav', 'Hindu', 'OBC', 'All India'),
('Kurmi', 'Hindu', 'OBC', 'North India'),
('Lodhi', 'Hindu', 'OBC', 'Madhya Pradesh'),

-- Vaishya Castes
('Vaishya', 'Hindu', 'General', 'All India'),
('Agarwal', 'Hindu', 'General', 'North India'),
('Baniya', 'Hindu', 'General', 'North India'),
('Maheshwari', 'Hindu', 'General', 'Rajasthan'),
('Khandelwal', 'Hindu', 'General', 'Rajasthan'),
('Oswal', 'Hindu', 'General', 'Rajasthan'),
('Porwal', 'Hindu', 'General', 'Rajasthan'),
('Jaiswal', 'Hindu', 'OBC', 'North India'),
('Gupta', 'Hindu', 'General', 'North India'),
('Bania', 'Hindu', 'General', 'Gujarat'),
('Arora', 'Hindu', 'General', 'Punjab'),
('Khatri', 'Hindu', 'General', 'Punjab'),
('Lohana', 'Hindu', 'General', 'Gujarat'),
('Bhatia', 'Hindu', 'General', 'Punjab, Sindh'),
('Komati', 'Hindu', 'General', 'Andhra Pradesh'),
('Chettiar', 'Hindu', 'OBC', 'Tamil Nadu'),
('Mudaliar', 'Hindu', 'OBC', 'Tamil Nadu'),
('Naicker', 'Hindu', 'OBC', 'Tamil Nadu'),
('Gounder', 'Hindu', 'OBC', 'Tamil Nadu'),
('Balija', 'Hindu', 'OBC', 'Andhra Pradesh'),

-- OBC Castes
('Ezhava', 'Hindu', 'OBC', 'Kerala'),
('Thiyya', 'Hindu', 'OBC', 'Kerala'),
('Vishwakarma', 'Hindu', 'OBC', 'All India'),
('Achari', 'Hindu', 'OBC', 'South India'),
('Asari', 'Hindu', 'OBC', 'Kerala'),
('Kallar', 'Hindu', 'OBC', 'Tamil Nadu'),
('Thevar', 'Hindu', 'OBC', 'Tamil Nadu'),
('Vanniyar', 'Hindu', 'OBC', 'Tamil Nadu'),
('Patidar', 'Hindu', 'OBC', 'Gujarat'),
('Patel', 'Hindu', 'OBC', 'Gujarat'),
('Kuruba', 'Hindu', 'OBC', 'Karnataka'),
('Bunt', 'Hindu', 'General', 'Karnataka'),
('Billava', 'Hindu', 'OBC', 'Karnataka'),
('Ediga', 'Hindu', 'OBC', 'Andhra Pradesh'),
('Gavara', 'Hindu', 'OBC', 'Andhra Pradesh'),
('Mala', 'Hindu', 'SC', 'Andhra Pradesh'),
('Madiga', 'Hindu', 'SC', 'Andhra Pradesh'),
('Chakali', 'Hindu', 'OBC', 'Andhra Pradesh'),
('Mangala', 'Hindu', 'OBC', 'Andhra Pradesh'),
('Khatik', 'Hindu', 'OBC', 'North India'),
('Dhangar', 'Hindu', 'OBC', 'Maharashtra'),
('Mali', 'Hindu', 'OBC', 'Maharashtra'),
('Teli', 'Hindu', 'OBC', 'North India'),
('Sonar', 'Hindu', 'OBC', 'Maharashtra'),
('Suthar', 'Hindu', 'OBC', 'Gujarat'),
('Ahir', 'Hindu', 'OBC', 'North India'),
('Koeri', 'Hindu', 'OBC', 'Bihar'),
('Kushwaha', 'Hindu', 'OBC', 'Bihar, UP'),
('Maurya', 'Hindu', 'OBC', 'Bihar, UP'),
('Saini', 'Hindu', 'OBC', 'Punjab, Haryana'),
('Koli', 'Hindu', 'OBC', 'Gujarat, Maharashtra'),
('Kunbi Maratha', 'Hindu', 'OBC', 'Maharashtra'),
('Sonar', 'Hindu', 'OBC', 'Maharashtra'),
('Lohar', 'Hindu', 'OBC', 'All India'),
('Badhai', 'Hindu', 'OBC', 'North India'),
('Kumhar', 'Hindu', 'OBC', 'All India'),
('Nai', 'Hindu', 'OBC', 'All India'),
('Darzi', 'Hindu', 'OBC', 'North India'),
('Dhobi', 'Hindu', 'SC', 'All India'),

-- SC/ST Castes
('Scheduled Caste', 'Hindu', 'SC', 'All India'),
('Scheduled Tribe', 'Hindu', 'ST', 'All India'),
('Chamar', 'Hindu', 'SC', 'North India'),
('Jatav', 'Hindu', 'SC', 'North India'),
('Balmiki', 'Hindu', 'SC', 'North India'),
('Khatik', 'Hindu', 'SC', 'North India'),
('Pasi', 'Hindu', 'SC', 'Uttar Pradesh'),
('Dusadh', 'Hindu', 'SC', 'Bihar'),
('Musahar', 'Hindu', 'SC', 'Bihar'),
('Bhil', 'Hindu', 'ST', 'Central India'),
('Gond', 'Hindu', 'ST', 'Central India'),
('Santhal', 'Hindu', 'ST', 'Eastern India'),
('Munda', 'Hindu', 'ST', 'Jharkhand'),
('Oraon', 'Hindu', 'ST', 'Jharkhand'),
('Meena', 'Hindu', 'ST', 'Rajasthan'),
('Bodo', 'Hindu', 'ST', 'Assam'),
('Mizo', 'Hindu', 'ST', 'Mizoram'),
('Naga', 'Hindu', 'ST', 'Nagaland'),
('Khasi', 'Hindu', 'ST', 'Meghalaya'),
('Garo', 'Hindu', 'ST', 'Meghalaya'),

-- Other Hindu Communities
('Sindhi', 'Hindu', 'General', 'All India'),
('Punjabi', 'Hindu', 'General', 'Punjab'),
('Kayastha', 'Hindu', 'General', 'North India'),
('Baidya', 'Hindu', 'General', 'West Bengal'),
('Vaishnav', 'Hindu', 'General', 'Gujarat'),
('Bania Vaishnav', 'Hindu', 'General', 'Gujarat'),
('Modh Ghanchi', 'Hindu', 'OBC', 'Gujarat'),
('Prajapati', 'Hindu', 'OBC', 'Gujarat'),
('Soni', 'Hindu', 'OBC', 'Gujarat'),

-- Muslim Communities
('Muslim', 'Islam', NULL, 'All India'),
('Sunni', 'Islam', NULL, 'All India'),
('Shia', 'Islam', NULL, 'All India'),
('Syed', 'Islam', NULL, 'All India'),
('Sheikh', 'Islam', NULL, 'All India'),
('Pathan', 'Islam', NULL, 'North India'),
('Mughal', 'Islam', NULL, 'North India'),
('Ansari', 'Islam', 'OBC', 'North India'),
('Qureshi', 'Islam', 'OBC', 'All India'),
('Khan', 'Islam', NULL, 'All India'),
('Malik', 'Islam', 'OBC', 'North India'),
('Saifi', 'Islam', 'OBC', 'North India'),
('Rajput Muslim', 'Islam', NULL, 'North India'),
('Memon', 'Islam', NULL, 'Gujarat'),
('Khoja', 'Islam', NULL, 'Gujarat'),
('Bohra', 'Islam', NULL, 'Gujarat'),
('Mapila', 'Islam', NULL, 'Kerala'),

-- Christian Communities
('Christian', 'Christian', NULL, 'All India'),
('Roman Catholic', 'Christian', NULL, 'All India'),
('Protestant', 'Christian', NULL, 'All India'),
('Latin Catholic', 'Christian', NULL, 'Kerala, Goa'),
('Syrian Christian', 'Christian', NULL, 'Kerala'),
('Knanaya Catholic', 'Christian', NULL, 'Kerala'),
('Jacobite', 'Christian', NULL, 'Kerala'),
('Malankara', 'Christian', NULL, 'Kerala'),
('Pentecostal', 'Christian', NULL, 'South India'),
('CSI', 'Christian', NULL, 'South India'),
('CNI', 'Christian', NULL, 'North India'),
('Anglo-Indian', 'Christian', NULL, 'All India'),

-- Sikh Communities
('Sikh', 'Sikh', NULL, 'All India'),
('Jat Sikh', 'Sikh', NULL, 'Punjab'),
('Khatri Sikh', 'Sikh', NULL, 'Punjab'),
('Arora Sikh', 'Sikh', NULL, 'Punjab'),
('Ramgarhia', 'Sikh', NULL, 'Punjab'),
('Saini Sikh', 'Sikh', NULL, 'Punjab'),
('Lubana Sikh', 'Sikh', NULL, 'Punjab'),
('Bhatra Sikh', 'Sikh', NULL, 'Punjab'),
('Ramdasia', 'Sikh', NULL, 'Punjab'),
('Mazhabi Sikh', 'Sikh', NULL, 'Punjab'),

-- Jain Communities
('Jain', 'Jain', NULL, 'All India'),
('Digambar Jain', 'Jain', NULL, 'All India'),
('Shwetambar Jain', 'Jain', NULL, 'All India'),
('Jain Agarwal', 'Jain', NULL, 'North India'),
('Jain Maheshwari', 'Jain', NULL, 'Rajasthan'),
('Jain Oswal', 'Jain', NULL, 'Rajasthan'),

-- Buddhist Communities
('Buddhist', 'Buddhist', NULL, 'All India'),
('Navayana Buddhist', 'Buddhist', 'SC', 'Maharashtra'),
('Tibetan Buddhist', 'Buddhist', NULL, 'North India'),
('Mahar', 'Buddhist', 'SC', 'Maharashtra'),

-- Parsi Communities
('Parsi', 'Zoroastrian', NULL, 'All India'),
('Irani', 'Zoroastrian', NULL, 'All India'),

-- Other Communities
('Sindhi', 'Hindu', 'General', 'All India'),
('Punjabi', 'Hindu', 'General', 'Punjab'),
('Bengali', 'Hindu', 'General', 'West Bengal'),
('Marwari', 'Hindu', 'General', 'Rajasthan'),
('Gujarati', 'Hindu', 'General', 'Gujarat'),
('Tamil', 'Hindu', 'General', 'Tamil Nadu'),
('Telugu', 'Hindu', 'General', 'Andhra Pradesh'),
('Kannada', 'Hindu', 'General', 'Karnataka'),
('Malayalam', 'Hindu', 'General', 'Kerala'),
('Odia', 'Hindu', 'General', 'Odisha'),
('Assamese', 'Hindu', 'General', 'Assam'),
('Kashmiri', 'Hindu', 'General', 'Jammu & Kashmir'),

-- Inter-caste/Other
('Inter-Caste', 'Hindu', NULL, 'All India'),
('Caste No Bar', 'All Religions', NULL, 'All India'),
('Others', 'All Religions', NULL, 'All India');
