<?php
/**
 * PHP Matrimony - Installation Wizard
 * ====================================
 * 
 * This script helps you set up the application on a new server.
 * 
 * SECURITY: Delete this file after successful installation!
 */

session_start();

// Prevent access if already installed
if (file_exists('config.php') && file_exists('.installed')) {
    die('
        <h1>Already Installed</h1>
        <p>This application is already installed.</p>
        <p>If you need to reinstall, delete the <code>.installed</code> file.</p>
        <p><a href="index.php">Go to Homepage</a> | <a href="admin/">Go to Admin</a></p>
    ');
}

$step = isset($_GET['step']) ? intval($_GET['step']) : 1;
$error = '';
$success = '';

// Process form submissions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    
    // Step 1: Check Requirements
    if (isset($_POST['check_requirements'])) {
        $step = 2;
    }
    
    // Step 2: Database Configuration
    if (isset($_POST['test_database'])) {
        $db_host = trim($_POST['db_host']);
        $db_name = trim($_POST['db_name']);
        $db_user = trim($_POST['db_user']);
        $db_pass = $_POST['db_pass'];
        
        // Test connection
        $conn = @mysqli_connect($db_host, $db_user, $db_pass, $db_name);
        
        if ($conn) {
            $_SESSION['db_config'] = [
                'host' => $db_host,
                'name' => $db_name,
                'user' => $db_user,
                'pass' => $db_pass
            ];
            mysqli_close($conn);
            $step = 3;
        } else {
            $error = 'Database connection failed: ' . mysqli_connect_error();
        }
    }
    
    // Step 3: Site Configuration
    if (isset($_POST['save_config'])) {
        $site_url = rtrim(trim($_POST['site_url']), '/');
        $site_name = trim($_POST['site_name']);
        $admin_email = trim($_POST['admin_email']);
        
        if (empty($site_url) || empty($site_name)) {
            $error = 'Please fill in all required fields.';
        } else {
            $_SESSION['site_config'] = [
                'url' => $site_url,
                'name' => $site_name,
                'email' => $admin_email
            ];
            $step = 4;
        }
    }
    
    // Step 4: Create Config & Install
    if (isset($_POST['install'])) {
        $db = $_SESSION['db_config'];
        $site = $_SESSION['site_config'];
        
        // Generate config.php content
        $config_content = '<?php
/**
 * PHP Matrimony Configuration File
 * Generated on: ' . date('Y-m-d H:i:s') . '
 */

// Environment
define(\'ENVIRONMENT\', \'production\');
define(\'DEBUG_MODE\', false);
define(\'SITE_URL\', \'' . addslashes($site['url']) . '\');
define(\'SITE_NAME\', \'' . addslashes($site['name']) . '\');

// Database
define(\'DB_HOST\', \'' . addslashes($db['host']) . '\');
define(\'DB_NAME\', \'' . addslashes($db['name']) . '\');
define(\'DB_USER\', \'' . addslashes($db['user']) . '\');
define(\'DB_PASS\', \'' . addslashes($db['pass']) . '\');

// File Upload Settings
define(\'MAX_UPLOAD_SIZE\', 5242880);
define(\'ALLOWED_IMAGE_TYPES\', \'jpg,jpeg,png,gif,webp\');
define(\'UPLOAD_DIR\', \'uploads/\');
define(\'PROFILE_DIR\', \'profile/\');

// Email Settings
define(\'SMTP_ENABLED\', false);
define(\'SMTP_HOST\', \'smtp.hostinger.com\');
define(\'SMTP_PORT\', 587);
define(\'SMTP_USER\', \'' . addslashes($site['email']) . '\');
define(\'SMTP_PASS\', \'\');
define(\'SMTP_FROM_NAME\', \'' . addslashes($site['name']) . '\');

// SMS Settings
define(\'SMS_GATEWAY\', \'disabled\');
define(\'TWILIO_SID\', \'\');
define(\'TWILIO_AUTH_TOKEN\', \'\');
define(\'TWILIO_FROM_NUMBER\', \'\');

// Payment Settings
define(\'PAYMENT_GATEWAY\', \'disabled\');
define(\'STRIPE_PUBLIC_KEY\', \'\');
define(\'STRIPE_SECRET_KEY\', \'\');

// Security Settings
define(\'SESSION_TIMEOUT\', 1800);
define(\'MAX_LOGIN_ATTEMPTS\', 5);
define(\'LOCKOUT_DURATION\', 15);
define(\'FORCE_HTTPS\', true);

// Admin Settings
define(\'DEFAULT_ADMIN_USER\', \'admin\');
define(\'ADMIN_ITEMS_PER_PAGE\', 20);

// Error reporting for production
error_reporting(0);
ini_set(\'display_errors\', 0);
ini_set(\'log_errors\', 1);
date_default_timezone_set(\'Asia/Kolkata\');
';
        
        // Save config.php
        if (file_put_contents('config.php', $config_content)) {
            
            // Update dbconn.php
            $dbconn_content = '<?php 
/*
 * DATABASE CONNECTION FILE
 * Auto-generated by installer on: ' . date('Y-m-d H:i:s') . '
 */

// Load config if exists
if (file_exists(__DIR__ . \'/../config.php\')) {
    require_once(__DIR__ . \'/../config.php\');
    $host = DB_HOST;
    $username = DB_USER;
    $password = DB_PASS;
    $db_name = DB_NAME;
} else {
    // Fallback configuration
    $host = "' . addslashes($db['host']) . '";
    $username = "' . addslashes($db['user']) . '";
    $password = "' . addslashes($db['pass']) . '";
    $db_name = "' . addslashes($db['name']) . '";
}

$conn = mysqli_connect($host, $username, $password, $db_name);

if (!$conn) {
    die("Database Connection Failed: " . mysqli_connect_error());
}

mysqli_set_charset($conn, "utf8mb4");
?>';
            
            file_put_contents('includes/dbconn.php', $dbconn_content);
            
            // Create .installed marker
            file_put_contents('.installed', date('Y-m-d H:i:s'));
            
            // Create required directories
            @mkdir('uploads', 0755, true);
            @mkdir('uploads/homepage', 0755, true);
            @mkdir('uploads/banners', 0755, true);
            @mkdir('profile', 0755, true);
            
            // Clear session
            unset($_SESSION['db_config']);
            unset($_SESSION['site_config']);
            
            $step = 5;
        } else {
            $error = 'Failed to create config.php. Please check file permissions.';
        }
    }
}

// Check server requirements
function checkRequirements() {
    $requirements = [];
    
    // PHP Version
    $requirements['php_version'] = [
        'name' => 'PHP Version',
        'required' => '8.0+',
        'current' => PHP_VERSION,
        'status' => version_compare(PHP_VERSION, '8.0.0', '>=')
    ];
    
    // PHP Extensions
    $extensions = ['mysqli', 'json', 'session', 'mbstring', 'gd'];
    foreach ($extensions as $ext) {
        $requirements['ext_' . $ext] = [
            'name' => 'PHP Extension: ' . $ext,
            'required' => 'Enabled',
            'current' => extension_loaded($ext) ? 'Enabled' : 'Not Found',
            'status' => extension_loaded($ext)
        ];
    }
    
    // Writable directories
    $dirs = ['uploads', 'profile', 'includes'];
    foreach ($dirs as $dir) {
        $writable = is_writable($dir) || (!file_exists($dir) && is_writable('.'));
        $requirements['dir_' . $dir] = [
            'name' => 'Directory: ' . $dir,
            'required' => 'Writable',
            'current' => $writable ? 'Writable' : 'Not Writable',
            'status' => $writable
        ];
    }
    
    return $requirements;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Install - PHP Matrimony</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 40px 0;
        }
        .install-container {
            max-width: 700px;
            margin: 0 auto;
        }
        .card {
            border: none;
            border-radius: 15px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
        }
        .card-header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border-radius: 15px 15px 0 0 !important;
            padding: 25px;
        }
        .step-indicator {
            display: flex;
            justify-content: center;
            margin-bottom: 30px;
        }
        .step {
            width: 40px;
            height: 40px;
            border-radius: 50%;
            background: rgba(255,255,255,0.3);
            color: white;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0 10px;
            font-weight: bold;
        }
        .step.active {
            background: white;
            color: #667eea;
        }
        .step.completed {
            background: #28a745;
        }
        .step-line {
            width: 30px;
            height: 2px;
            background: rgba(255,255,255,0.3);
            margin-top: 19px;
        }
        .requirement-item {
            padding: 12px 15px;
            border-bottom: 1px solid #eee;
        }
        .requirement-item:last-child {
            border-bottom: none;
        }
        .btn-primary {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            border: none;
            padding: 12px 30px;
        }
        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 5px 20px rgba(102, 126, 234, 0.4);
        }
        .success-icon {
            font-size: 80px;
            color: #28a745;
        }
    </style>
</head>
<body>
    <div class="install-container">
        <div class="card">
            <div class="card-header text-center">
                <h2><i class="fas fa-heart"></i> PHP Matrimony</h2>
                <p class="mb-0">Installation Wizard</p>
                
                <!-- Step Indicator -->
                <div class="step-indicator mt-4">
                    <div class="step <?php echo $step >= 1 ? ($step > 1 ? 'completed' : 'active') : ''; ?>">
                        <?php echo $step > 1 ? '<i class="fas fa-check"></i>' : '1'; ?>
                    </div>
                    <div class="step-line"></div>
                    <div class="step <?php echo $step >= 2 ? ($step > 2 ? 'completed' : 'active') : ''; ?>">
                        <?php echo $step > 2 ? '<i class="fas fa-check"></i>' : '2'; ?>
                    </div>
                    <div class="step-line"></div>
                    <div class="step <?php echo $step >= 3 ? ($step > 3 ? 'completed' : 'active') : ''; ?>">
                        <?php echo $step > 3 ? '<i class="fas fa-check"></i>' : '3'; ?>
                    </div>
                    <div class="step-line"></div>
                    <div class="step <?php echo $step >= 4 ? ($step > 4 ? 'completed' : 'active') : ''; ?>">
                        <?php echo $step > 4 ? '<i class="fas fa-check"></i>' : '4'; ?>
                    </div>
                    <div class="step-line"></div>
                    <div class="step <?php echo $step >= 5 ? 'active' : ''; ?>">5</div>
                </div>
            </div>
            
            <div class="card-body p-4">
                <?php if ($error): ?>
                <div class="alert alert-danger">
                    <i class="fas fa-exclamation-circle"></i> <?php echo htmlspecialchars($error); ?>
                </div>
                <?php endif; ?>
                
                <?php if ($step == 1): ?>
                <!-- Step 1: Requirements Check -->
                <h4 class="mb-4"><i class="fas fa-clipboard-check"></i> Step 1: Check Requirements</h4>
                
                <?php $requirements = checkRequirements(); ?>
                
                <div class="bg-light rounded p-3 mb-4">
                    <?php foreach ($requirements as $req): ?>
                    <div class="requirement-item d-flex justify-content-between align-items-center">
                        <div>
                            <strong><?php echo $req['name']; ?></strong>
                            <br><small class="text-muted">Required: <?php echo $req['required']; ?></small>
                        </div>
                        <div class="text-end">
                            <span class="badge bg-<?php echo $req['status'] ? 'success' : 'danger'; ?>">
                                <?php echo $req['current']; ?>
                            </span>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
                
                <?php 
                $allPassed = true;
                foreach ($requirements as $req) {
                    if (!$req['status']) $allPassed = false;
                }
                ?>
                
                <?php if ($allPassed): ?>
                <form method="post">
                    <button type="submit" name="check_requirements" class="btn btn-primary btn-lg w-100">
                        Continue <i class="fas fa-arrow-right"></i>
                    </button>
                </form>
                <?php else: ?>
                <div class="alert alert-warning">
                    <i class="fas fa-exclamation-triangle"></i> Please fix the above requirements before continuing.
                </div>
                <?php endif; ?>
                
                <?php elseif ($step == 2): ?>
                <!-- Step 2: Database Configuration -->
                <h4 class="mb-4"><i class="fas fa-database"></i> Step 2: Database Configuration</h4>
                
                <div class="alert alert-info">
                    <i class="fas fa-info-circle"></i> 
                    <strong>Hostinger Users:</strong> Find your database credentials in cPanel → MySQL Databases
                </div>
                
                <form method="post">
                    <div class="mb-3">
                        <label class="form-label">Database Host</label>
                        <input type="text" name="db_host" class="form-control" value="localhost" required>
                        <small class="text-muted">Usually 'localhost' for Hostinger</small>
                    </div>
                    
                    <div class="mb-3">
                        <label class="form-label">Database Name</label>
                        <input type="text" name="db_name" class="form-control" placeholder="cpanelusername_matrimony" required>
                        <small class="text-muted">Example: abcd1234_matrimony</small>
                    </div>
                    
                    <div class="mb-3">
                        <label class="form-label">Database Username</label>
                        <input type="text" name="db_user" class="form-control" placeholder="cpanelusername_dbuser" required>
                        <small class="text-muted">Example: abcd1234_dbuser</small>
                    </div>
                    
                    <div class="mb-3">
                        <label class="form-label">Database Password</label>
                        <input type="password" name="db_pass" class="form-control" required>
                    </div>
                    
                    <button type="submit" name="test_database" class="btn btn-primary btn-lg w-100">
                        Test Connection & Continue <i class="fas fa-arrow-right"></i>
                    </button>
                </form>
                
                <?php elseif ($step == 3): ?>
                <!-- Step 3: Site Configuration -->
                <h4 class="mb-4"><i class="fas fa-globe"></i> Step 3: Site Configuration</h4>
                
                <form method="post">
                    <div class="mb-3">
                        <label class="form-label">Site URL</label>
                        <input type="url" name="site_url" class="form-control" 
                               value="<?php echo 'https://' . $_SERVER['HTTP_HOST']; ?>" required>
                        <small class="text-muted">Your website address (without trailing slash)</small>
                    </div>
                    
                    <div class="mb-3">
                        <label class="form-label">Site Name</label>
                        <input type="text" name="site_name" class="form-control" value="MakeMyLove" required>
                        <small class="text-muted">Displayed in header and emails</small>
                    </div>
                    
                    <div class="mb-3">
                        <label class="form-label">Admin Email</label>
                        <input type="email" name="admin_email" class="form-control" placeholder="admin@yourdomain.com">
                        <small class="text-muted">For notifications and password recovery</small>
                    </div>
                    
                    <button type="submit" name="save_config" class="btn btn-primary btn-lg w-100">
                        Continue <i class="fas fa-arrow-right"></i>
                    </button>
                </form>
                
                <?php elseif ($step == 4): ?>
                <!-- Step 4: Confirm & Install -->
                <h4 class="mb-4"><i class="fas fa-cogs"></i> Step 4: Confirm Installation</h4>
                
                <div class="alert alert-warning">
                    <i class="fas fa-exclamation-triangle"></i>
                    <strong>Before clicking Install:</strong>
                    <ul class="mb-0 mt-2">
                        <li>Make sure you have imported the database (<code>db/matrimony.sql</code>)</li>
                        <li>Review the configuration below</li>
                    </ul>
                </div>
                
                <div class="bg-light rounded p-3 mb-4">
                    <h6>Database Configuration</h6>
                    <p class="mb-1"><strong>Host:</strong> <?php echo htmlspecialchars($_SESSION['db_config']['host']); ?></p>
                    <p class="mb-1"><strong>Database:</strong> <?php echo htmlspecialchars($_SESSION['db_config']['name']); ?></p>
                    <p class="mb-3"><strong>User:</strong> <?php echo htmlspecialchars($_SESSION['db_config']['user']); ?></p>
                    
                    <h6>Site Configuration</h6>
                    <p class="mb-1"><strong>URL:</strong> <?php echo htmlspecialchars($_SESSION['site_config']['url']); ?></p>
                    <p class="mb-1"><strong>Name:</strong> <?php echo htmlspecialchars($_SESSION['site_config']['name']); ?></p>
                    <p class="mb-0"><strong>Email:</strong> <?php echo htmlspecialchars($_SESSION['site_config']['email'] ?: 'Not set'); ?></p>
                </div>
                
                <form method="post">
                    <button type="submit" name="install" class="btn btn-success btn-lg w-100">
                        <i class="fas fa-check-circle"></i> Install Now
                    </button>
                </form>
                
                <a href="install.php?step=2" class="btn btn-link w-100 mt-2">
                    <i class="fas fa-arrow-left"></i> Go Back
                </a>
                
                <?php elseif ($step == 5): ?>
                <!-- Step 5: Complete -->
                <div class="text-center">
                    <div class="success-icon mb-4">
                        <i class="fas fa-check-circle"></i>
                    </div>
                    <h3 class="text-success mb-3">Installation Complete!</h3>
                    <p class="text-muted mb-4">
                        Your matrimony portal has been successfully installed.
                    </p>
                    
                    <div class="alert alert-info text-start">
                        <h6><i class="fas fa-key"></i> Default Admin Credentials:</h6>
                        <p class="mb-1"><strong>Username:</strong> admin</p>
                        <p class="mb-0"><strong>Password:</strong> admin123</p>
                        <hr>
                        <small class="text-danger"><i class="fas fa-exclamation-triangle"></i> Change these immediately after login!</small>
                    </div>
                    
                    <div class="alert alert-warning text-start">
                        <h6><i class="fas fa-trash-alt"></i> Security Reminder:</h6>
                        <p class="mb-0">Delete <code>install.php</code> from your server for security.</p>
                    </div>
                    
                    <div class="d-grid gap-2">
                        <a href="index.php" class="btn btn-primary btn-lg">
                            <i class="fas fa-home"></i> Go to Homepage
                        </a>
                        <a href="admin/" class="btn btn-outline-primary">
                            <i class="fas fa-lock"></i> Go to Admin Panel
                        </a>
                    </div>
                </div>
                <?php endif; ?>
            </div>
        </div>
        
        <p class="text-center text-white mt-4">
            <small>PHP Matrimony © <?php echo date('Y'); ?></small>
        </p>
    </div>
</body>
</html>
