-- Migration: Add Indian Cities Table
-- Created: 2025-11-19

-- Create cities table
CREATE TABLE IF NOT EXISTS `cities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(100) NOT NULL,
  `state_id` INT(11) NOT NULL,
  `state_code` VARCHAR(10) NOT NULL,
  `is_major` TINYINT(1) DEFAULT 0 COMMENT '1 for major cities',
  `population` INT(11) DEFAULT NULL,
  `status` TINYINT(1) DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_state_id` (`state_id`),
  KEY `idx_state_code` (`state_code`),
  KEY `idx_city_name` (`city_name`),
  KEY `idx_is_major` (`is_major`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert major Indian cities (Top 500+ cities)

-- Andhra Pradesh
INSERT INTO `cities` (`city_name`, `state_id`, `state_code`, `is_major`) VALUES
('Visakhapatnam', 1, 'AP', 1),
('Vijayawada', 1, 'AP', 1),
('Guntur', 1, 'AP', 1),
('Nellore', 1, 'AP', 1),
('Kurnool', 1, 'AP', 1),
('Kakinada', 1, 'AP', 1),
('Rajahmundry', 1, 'AP', 1),
('Tirupati', 1, 'AP', 1),
('Kadapa', 1, 'AP', 1),
('Anantapur', 1, 'AP', 1),
('Vizianagaram', 1, 'AP', 0),
('Eluru', 1, 'AP', 0),
('Ongole', 1, 'AP', 0),
('Nandyal', 1, 'AP', 0),
('Machilipatnam', 1, 'AP', 0),
('Adoni', 1, 'AP', 0),
('Tenali', 1, 'AP', 0),
('Chittoor', 1, 'AP', 0),
('Hindupur', 1, 'AP', 0),
('Proddatur', 1, 'AP', 0),
('Bhimavaram', 1, 'AP', 0),
('Madanapalle', 1, 'AP', 0),
('Guntakal', 1, 'AP', 0),
('Dharmavaram', 1, 'AP', 0),
('Gudivada', 1, 'AP', 0),
('Srikakulam', 1, 'AP', 0),
('Narasaraopet', 1, 'AP', 0),
('Tadipatri', 1, 'AP', 0),
('Tadepalligudem', 1, 'AP', 0),
('Chilakaluripet', 1, 'AP', 0),

-- Arunachal Pradesh
('Itanagar', 2, 'AR', 1),
('Naharlagun', 2, 'AR', 0),
('Pasighat', 2, 'AR', 0),
('Tawang', 2, 'AR', 0),
('Ziro', 2, 'AR', 0),
('Bomdila', 2, 'AR', 0),
('Tezu', 2, 'AR', 0),
('Seppa', 2, 'AR', 0),
('Along', 2, 'AR', 0),
('Roing', 2, 'AR', 0),

-- Assam
('Guwahati', 3, 'AS', 1),
('Silchar', 3, 'AS', 1),
('Dibrugarh', 3, 'AS', 1),
('Jorhat', 3, 'AS', 0),
('Nagaon', 3, 'AS', 0),
('Tinsukia', 3, 'AS', 0),
('Tezpur', 3, 'AS', 0),
('Bongaigaon', 3, 'AS', 0),
('Dhubri', 3, 'AS', 0),
('Diphu', 3, 'AS', 0),
('North Lakhimpur', 3, 'AS', 0),
('Karimganj', 3, 'AS', 0),
('Goalpara', 3, 'AS', 0),
('Sivasagar', 3, 'AS', 0),
('Golaghat', 3, 'AS', 0),
('Barpeta', 3, 'AS', 0),
('Hojai', 3, 'AS', 0),
('Mangaldoi', 3, 'AS', 0),
('Lumding', 3, 'AS', 0),
('Haflong', 3, 'AS', 0),

-- Bihar
('Patna', 4, 'BR', 1),
('Gaya', 4, 'BR', 1),
('Bhagalpur', 4, 'BR', 1),
('Muzaffarpur', 4, 'BR', 1),
('Darbhanga', 4, 'BR', 1),
('Purnia', 4, 'BR', 0),
('Bihar Sharif', 4, 'BR', 0),
('Arrah', 4, 'BR', 0),
('Begusarai', 4, 'BR', 0),
('Katihar', 4, 'BR', 0),
('Munger', 4, 'BR', 0),
('Chhapra', 4, 'BR', 0),
('Danapur', 4, 'BR', 0),
('Saharsa', 4, 'BR', 0),
('Sasaram', 4, 'BR', 0),
('Hajipur', 4, 'BR', 0),
('Dehri', 4, 'BR', 0),
('Siwan', 4, 'BR', 0),
('Motihari', 4, 'BR', 0),
('Nawada', 4, 'BR', 0),
('Bagaha', 4, 'BR', 0),
('Buxar', 4, 'BR', 0),
('Kishanganj', 4, 'BR', 0),
('Sitamarhi', 4, 'BR', 0),
('Jamalpur', 4, 'BR', 0),
('Jehanabad', 4, 'BR', 0),
('Aurangabad', 4, 'BR', 0),

-- Chhattisgarh
('Raipur', 5, 'CG', 1),
('Bhilai', 5, 'CG', 1),
('Bilaspur', 5, 'CG', 1),
('Korba', 5, 'CG', 0),
('Durg', 5, 'CG', 0),
('Rajnandgaon', 5, 'CG', 0),
('Raigarh', 5, 'CG', 0),
('Jagdalpur', 5, 'CG', 0),
('Ambikapur', 5, 'CG', 0),
('Mahasamund', 5, 'CG', 0),
('Dhamtari', 5, 'CG', 0),
('Chirmiri', 5, 'CG', 0),
('Bhatapara', 5, 'CG', 0),
('Dalli-Rajhara', 5, 'CG', 0),
('Naila Janjgir', 5, 'CG', 0),

-- Goa
('Panaji', 6, 'GA', 1),
('Margao', 6, 'GA', 1),
('Vasco da Gama', 6, 'GA', 1),
('Mapusa', 6, 'GA', 0),
('Ponda', 6, 'GA', 0),
('Bicholim', 6, 'GA', 0),
('Curchorem', 6, 'GA', 0),
('Sanquelim', 6, 'GA', 0),
('Cuncolim', 6, 'GA', 0),
('Quepem', 6, 'GA', 0),

-- Gujarat
('Ahmedabad', 7, 'GJ', 1),
('Surat', 7, 'GJ', 1),
('Vadodara', 7, 'GJ', 1),
('Rajkot', 7, 'GJ', 1),
('Bhavnagar', 7, 'GJ', 1),
('Jamnagar', 7, 'GJ', 1),
('Junagadh', 7, 'GJ', 0),
('Gandhidham', 7, 'GJ', 0),
('Nadiad', 7, 'GJ', 0),
('Morbi', 7, 'GJ', 0),
('Surendranagar', 7, 'GJ', 0),
('Bharuch', 7, 'GJ', 0),
('Anand', 7, 'GJ', 0),
('Porbandar', 7, 'GJ', 0),
('Godhra', 7, 'GJ', 0),
('Botad', 7, 'GJ', 0),
('Veraval', 7, 'GJ', 0),
('Gandhinagar', 7, 'GJ', 0),
('Navsari', 7, 'GJ', 0),
('Valsad', 7, 'GJ', 0),
('Vapi', 7, 'GJ', 0),
('Mehsana', 7, 'GJ', 0),
('Patan', 7, 'GJ', 0),
('Palanpur', 7, 'GJ', 0),
('Bhuj', 7, 'GJ', 0),
('Ankleshwar', 7, 'GJ', 0),
('Deesa', 7, 'GJ', 0),
('Kalol', 7, 'GJ', 0),
('Dahod', 7, 'GJ', 0),
('Amreli', 7, 'GJ', 0),

-- Haryana
('Faridabad', 8, 'HR', 1),
('Gurgaon', 8, 'HR', 1),
('Panipat', 8, 'HR', 1),
('Ambala', 8, 'HR', 1),
('Yamunanagar', 8, 'HR', 0),
('Rohtak', 8, 'HR', 0),
('Hisar', 8, 'HR', 0),
('Karnal', 8, 'HR', 0),
('Sonipat', 8, 'HR', 0),
('Panchkula', 8, 'HR', 0),
('Bhiwani', 8, 'HR', 0),
('Sirsa', 8, 'HR', 0),
('Bahadurgarh', 8, 'HR', 0),
('Jind', 8, 'HR', 0),
('Thanesar', 8, 'HR', 0),
('Kaithal', 8, 'HR', 0),
('Rewari', 8, 'HR', 0),
('Palwal', 8, 'HR', 0),
('Hansi', 8, 'HR', 0),
('Narnaul', 8, 'HR', 0),

-- Himachal Pradesh
('Shimla', 9, 'HP', 1),
('Dharamshala', 9, 'HP', 1),
('Solan', 9, 'HP', 0),
('Mandi', 9, 'HP', 0),
('Palampur', 9, 'HP', 0),
('Kullu', 9, 'HP', 0),
('Hamirpur', 9, 'HP', 0),
('Una', 9, 'HP', 0),
('Bilaspur', 9, 'HP', 0),
('Chamba', 9, 'HP', 0),
('Nahan', 9, 'HP', 0),
('Sundernagar', 9, 'HP', 0),
('Kangra', 9, 'HP', 0),
('Baddi', 9, 'HP', 0),
('Nalagarh', 9, 'HP', 0),

-- Jharkhand
('Ranchi', 10, 'JH', 1),
('Jamshedpur', 10, 'JH', 1),
('Dhanbad', 10, 'JH', 1),
('Bokaro', 10, 'JH', 1),
('Deoghar', 10, 'JH', 0),
('Phusro', 10, 'JH', 0),
('Hazaribagh', 10, 'JH', 0),
('Giridih', 10, 'JH', 0),
('Ramgarh', 10, 'JH', 0),
('Medininagar', 10, 'JH', 0),
('Chirkunda', 10, 'JH', 0),
('Dumka', 10, 'JH', 0),
('Chaibasa', 10, 'JH', 0),
('Gumla', 10, 'JH', 0),
('Mihijam', 10, 'JH', 0),
('Jhumri Tilaiya', 10, 'JH', 0),
('Saunda', 10, 'JH', 0),
('Sahibganj', 10, 'JH', 0),
('Madhupur', 10, 'JH', 0),
('Godda', 10, 'JH', 0),

-- Karnataka
('Bangalore', 11, 'KA', 1),
('Mysore', 11, 'KA', 1),
('Hubli', 11, 'KA', 1),
('Mangalore', 11, 'KA', 1),
('Belgaum', 11, 'KA', 1),
('Gulbarga', 11, 'KA', 1),
('Davanagere', 11, 'KA', 1),
('Bellary', 11, 'KA', 0),
('Bijapur', 11, 'KA', 0),
('Shimoga', 11, 'KA', 0),
('Tumkur', 11, 'KA', 0),
('Raichur', 11, 'KA', 0),
('Bidar', 11, 'KA', 0),
('Hospet', 11, 'KA', 0),
('Hassan', 11, 'KA', 0),
('Gadag-Betigeri', 11, 'KA', 0),
('Udupi', 11, 'KA', 0),
('Robertson Pet', 11, 'KA', 0),
('Bhadravati', 11, 'KA', 0),
('Chitradurga', 11, 'KA', 0),
('Kolar', 11, 'KA', 0),
('Mandya', 11, 'KA', 0),
('Chikmagalur', 11, 'KA', 0),
('Gangavati', 11, 'KA', 0),
('Bagalkot', 11, 'KA', 0),
('Ranibennur', 11, 'KA', 0),

-- Kerala
('Thiruvananthapuram', 12, 'KL', 1),
('Kochi', 12, 'KL', 1),
('Kozhikode', 12, 'KL', 1),
('Thrissur', 12, 'KL', 1),
('Kollam', 12, 'KL', 1),
('Palakkad', 12, 'KL', 0),
('Alappuzha', 12, 'KL', 0),
('Malappuram', 12, 'KL', 0),
('Kannur', 12, 'KL', 0),
('Kottayam', 12, 'KL', 0),
('Kasaragod', 12, 'KL', 0),
('Manjeri', 12, 'KL', 0),
('Thalassery', 12, 'KL', 0),
('Ponnani', 12, 'KL', 0),
('Vatakara', 12, 'KL', 0),
('Kanhangad', 12, 'KL', 0),
('Payyanur', 12, 'KL', 0),
('Koyilandy', 12, 'KL', 0),
('Parappanangadi', 12, 'KL', 0),
('Kalamassery', 12, 'KL', 0),
('Neyyattinkara', 12, 'KL', 0),
('Changanassery', 12, 'KL', 0),
('Kayamkulam', 12, 'KL', 0),
('Nedumangad', 12, 'KL', 0),
('Kannur Cantonment', 12, 'KL', 0),
('Tirur', 12, 'KL', 0),
('Kottakkal', 12, 'KL', 0),
('Kasargod', 12, 'KL', 0),
('Kunnamkulam', 12, 'KL', 0),
('Ottappalam', 12, 'KL', 0),
('Thiruvalla', 12, 'KL', 0),
('Thodupuzha', 12, 'KL', 0),
('Chalakudy', 12, 'KL', 0),
('Changanacherry', 12, 'KL', 0),
('Punalur', 12, 'KL', 0),
('Nilambur', 12, 'KL', 0),
('Cherthala', 12, 'KL', 0),
('Perinthalmanna', 12, 'KL', 0),
('Mattannur', 12, 'KL', 0),
('Shoranur', 12, 'KL', 0),
('Varkala', 12, 'KL', 0),
('Paravur', 12, 'KL', 0),
('Pathanamthitta', 12, 'KL', 0),
('Peringathur', 12, 'KL', 0),
('Attingal', 12, 'KL', 0),
('Kodungallur', 12, 'KL', 0),
('Pappinisseri', 12, 'KL', 0),
('Chittur-Thathamangalam', 12, 'KL', 0),
('Muvattupuzha', 12, 'KL', 0),
('Adoor', 12, 'KL', 0),
('Mavelikkara', 12, 'KL', 0),

-- Madhya Pradesh
('Indore', 13, 'MP', 1),
('Bhopal', 13, 'MP', 1),
('Jabalpur', 13, 'MP', 1),
('Gwalior', 13, 'MP', 1),
('Ujjain', 13, 'MP', 1),
('Sagar', 13, 'MP', 0),
('Dewas', 13, 'MP', 0),
('Satna', 13, 'MP', 0),
('Ratlam', 13, 'MP', 0),
('Rewa', 13, 'MP', 0),
('Katni', 13, 'MP', 0),
('Singrauli', 13, 'MP', 0),
('Burhanpur', 13, 'MP', 0),
('Khandwa', 13, 'MP', 0),
('Morena', 13, 'MP', 0),
('Bhind', 13, 'MP', 0),
('Chhindwara', 13, 'MP', 0),
('Guna', 13, 'MP', 0),
('Shivpuri', 13, 'MP', 0),
('Vidisha', 13, 'MP', 0),
('Chhatarpur', 13, 'MP', 0),
('Damoh', 13, 'MP', 0),
('Mandsaur', 13, 'MP', 0),
('Khargone', 13, 'MP', 0),
('Neemuch', 13, 'MP', 0),
('Pithampur', 13, 'MP', 0),
('Hoshangabad', 13, 'MP', 0),
('Itarsi', 13, 'MP', 0),
('Sehore', 13, 'MP', 0),
('Betul', 13, 'MP', 0),

-- Maharashtra
('Mumbai', 14, 'MH', 1),
('Pune', 14, 'MH', 1),
('Nagpur', 14, 'MH', 1),
('Thane', 14, 'MH', 1),
('Nashik', 14, 'MH', 1),
('Aurangabad', 14, 'MH', 1),
('Solapur', 14, 'MH', 1),
('Kolhapur', 14, 'MH', 1),
('Amravati', 14, 'MH', 1),
('Navi Mumbai', 14, 'MH', 1),
('Sangli', 14, 'MH', 0),
('Malegaon', 14, 'MH', 0),
('Akola', 14, 'MH', 0),
('Latur', 14, 'MH', 0),
('Dhule', 14, 'MH', 0),
('Ahmednagar', 14, 'MH', 0),
('Ichalkaranji', 14, 'MH', 0),
('Parbhani', 14, 'MH', 0),
('Panvel', 14, 'MH', 0),
('Yavatmal', 14, 'MH', 0),
('Achalpur', 14, 'MH', 0),
('Osmanabad', 14, 'MH', 0),
('Nanded', 14, 'MH', 0),
('Satara', 14, 'MH', 0),
('Wardha', 14, 'MH', 0),
('Udgir', 14, 'MH', 0),
('Bid', 14, 'MH', 0),
('Jalgaon', 14, 'MH', 0),
('Gondia', 14, 'MH', 0),
('Jalna', 14, 'MH', 0),
('Palghar', 14, 'MH', 0),
('Beed', 14, 'MH', 0),
('Chandrapur', 14, 'MH', 0),
('Pimpri-Chinchwad', 14, 'MH', 0),
('Bhandara', 14, 'MH', 0),
('Bhusawal', 14, 'MH', 0),
('Ratnagiri', 14, 'MH', 0),

-- Manipur
('Imphal', 15, 'MN', 1),
('Thoubal', 15, 'MN', 0),
('Lilong', 15, 'MN', 0),
('Mayang Imphal', 15, 'MN', 0),
('Kakching', 15, 'MN', 0),

-- Meghalaya
('Shillong', 16, 'ML', 1),
('Tura', 16, 'ML', 0),
('Nongstoin', 16, 'ML', 0),
('Jowai', 16, 'ML', 0),

-- Mizoram
('Aizawl', 17, 'MZ', 1),
('Lunglei', 17, 'MZ', 0),
('Saiha', 17, 'MZ', 0),

-- Nagaland
('Kohima', 18, 'NL', 1),
('Dimapur', 18, 'NL', 1),
('Mokokchung', 18, 'NL', 0),
('Tuensang', 18, 'NL', 0),
('Wokha', 18, 'NL', 0),

-- Odisha
('Bhubaneswar', 19, 'OR', 1),
('Cuttack', 19, 'OR', 1),
('Rourkela', 19, 'OR', 1),
('Brahmapur', 19, 'OR', 1),
('Sambalpur', 19, 'OR', 0),
('Puri', 19, 'OR', 0),
('Balasore', 19, 'OR', 0),
('Baripada', 19, 'OR', 0),
('Bhadrak', 19, 'OR', 0),
('Balangir', 19, 'OR', 0),
('Jharsuguda', 19, 'OR', 0),
('Jeypore', 19, 'OR', 0),
('Bargarh', 19, 'OR', 0),
('Rayagada', 19, 'OR', 0),
('Bhawanipatna', 19, 'OR', 0),
('Dhenkanal', 19, 'OR', 0),
('Barbil', 19, 'OR', 0),
('Kendujhar', 19, 'OR', 0),
('Sunabeda', 19, 'OR', 0),
('Paradip', 19, 'OR', 0),

-- Punjab
('Ludhiana', 20, 'PB', 1),
('Amritsar', 20, 'PB', 1),
('Jalandhar', 20, 'PB', 1),
('Patiala', 20, 'PB', 1),
('Bathinda', 20, 'PB', 0),
('Mohali', 20, 'PB', 0),
('Pathankot', 20, 'PB', 0),
('Hoshiarpur', 20, 'PB', 0),
('Batala', 20, 'PB', 0),
('Moga', 20, 'PB', 0),
('Malerkotla', 20, 'PB', 0),
('Khanna', 20, 'PB', 0),
('Phagwara', 20, 'PB', 0),
('Muktsar', 20, 'PB', 0),
('Barnala', 20, 'PB', 0),
('Firozpur', 20, 'PB', 0),
('Kapurthala', 20, 'PB', 0),
('Faridkot', 20, 'PB', 0),
('Rajpura', 20, 'PB', 0),
('Sangrur', 20, 'PB', 0),

-- Rajasthan
('Jaipur', 21, 'RJ', 1),
('Jodhpur', 21, 'RJ', 1),
('Kota', 21, 'RJ', 1),
('Bikaner', 21, 'RJ', 1),
('Ajmer', 21, 'RJ', 1),
('Udaipur', 21, 'RJ', 1),
('Bhilwara', 21, 'RJ', 0),
('Alwar', 21, 'RJ', 0),
('Bharatpur', 21, 'RJ', 0),
('Pali', 21, 'RJ', 0),
('Barmer', 21, 'RJ', 0),
('Sikar', 21, 'RJ', 0),
('Tonk', 21, 'RJ', 0),
('Sadulpur', 21, 'RJ', 0),
('Sawai Madhopur', 21, 'RJ', 0),
('Nagaur', 21, 'RJ', 0),
('Makrana', 21, 'RJ', 0),
('Sujangarh', 21, 'RJ', 0),
('Sardarshahar', 21, 'RJ', 0),
('Churu', 21, 'RJ', 0),
('Jhunjhunu', 21, 'RJ', 0),
('Ganganagar', 21, 'RJ', 0),
('Hanumangarh', 21, 'RJ', 0),
('Beawar', 21, 'RJ', 0),
('Kishangarh', 21, 'RJ', 0),

-- Sikkim
('Gangtok', 22, 'SK', 1),
('Namchi', 22, 'SK', 0),
('Gyalshing', 22, 'SK', 0),
('Mangan', 22, 'SK', 0),
('Rangpo', 22, 'SK', 0),

-- Tamil Nadu
('Chennai', 23, 'TN', 1),
('Coimbatore', 23, 'TN', 1),
('Madurai', 23, 'TN', 1),
('Tiruchirappalli', 23, 'TN', 1),
('Salem', 23, 'TN', 1),
('Tirunelveli', 23, 'TN', 1),
('Tiruppur', 23, 'TN', 1),
('Ranipet', 23, 'TN', 0),
('Nagercoil', 23, 'TN', 0),
('Thanjavur', 23, 'TN', 0),
('Vellore', 23, 'TN', 0),
('Kancheepuram', 23, 'TN', 0),
('Erode', 23, 'TN', 0),
('Tiruvannamalai', 23, 'TN', 0),
('Pollachi', 23, 'TN', 0),
('Rajapalayam', 23, 'TN', 0),
('Sivakasi', 23, 'TN', 0),
('Pudukkottai', 23, 'TN', 0),
('Neyveli', 23, 'TN', 0),
('Nagapattinam', 23, 'TN', 0),
('Viluppuram', 23, 'TN', 0),
('Tiruchengode', 23, 'TN', 0),
('Vaniyambadi', 23, 'TN', 0),
('Theni Allinagaram', 23, 'TN', 0),
('Udhagamandalam', 23, 'TN', 0),
('Aruppukkottai', 23, 'TN', 0),
('Paramakudi', 23, 'TN', 0),
('Arakkonam', 23, 'TN', 0),
('Virudhachalam', 23, 'TN', 0),
('Srivilliputhur', 23, 'TN', 0),
('Tindivanam', 23, 'TN', 0),
('Virudhunagar', 23, 'TN', 0),
('Karur', 23, 'TN', 0),
('Cuddalore', 23, 'TN', 0),
('Kumbakonam', 23, 'TN', 0),
('Tirupattur', 23, 'TN', 0),
('Avadi', 23, 'TN', 0),
('Pallavaram', 23, 'TN', 0),
('Ambattur', 23, 'TN', 0),

-- Telangana
('Hyderabad', 24, 'TS', 1),
('Warangal', 24, 'TS', 1),
('Nizamabad', 24, 'TS', 0),
('Karimnagar', 24, 'TS', 0),
('Ramagundam', 24, 'TS', 0),
('Khammam', 24, 'TS', 0),
('Mahbubnagar', 24, 'TS', 0),
('Nalgonda', 24, 'TS', 0),
('Adilabad', 24, 'TS', 0),
('Suryapet', 24, 'TS', 0),
('Siddipet', 24, 'TS', 0),
('Miryalaguda', 24, 'TS', 0),
('Jagtial', 24, 'TS', 0),
('Mancherial', 24, 'TS', 0),
('Nirmal', 24, 'TS', 0),
('Peddapalli', 24, 'TS', 0),
('Wanaparthy', 24, 'TS', 0),
('Bodhan', 24, 'TS', 0),
('Palwancha', 24, 'TS', 0),
('Mandamarri', 24, 'TS', 0),

-- Tripura
('Agartala', 25, 'TR', 1),
('Udaipur', 25, 'TR', 0),
('Dharmanagar', 25, 'TR', 0),
('Pratapgarh', 25, 'TR', 0),
('Kailasahar', 25, 'TR', 0),
('Belonia', 25, 'TR', 0),
('Khowai', 25, 'TR', 0),

-- Uttar Pradesh
('Lucknow', 26, 'UP', 1),
('Kanpur', 26, 'UP', 1),
('Ghaziabad', 26, 'UP', 1),
('Agra', 26, 'UP', 1),
('Meerut', 26, 'UP', 1),
('Varanasi', 26, 'UP', 1),
('Prayagraj', 26, 'UP', 1),
('Bareilly', 26, 'UP', 1),
('Aligarh', 26, 'UP', 1),
('Moradabad', 26, 'UP', 1),
('Saharanpur', 26, 'UP', 1),
('Gorakhpur', 26, 'UP', 1),
('Noida', 26, 'UP', 1),
('Firozabad', 26, 'UP', 0),
('Jhansi', 26, 'UP', 0),
('Muzaffarnagar', 26, 'UP', 0),
('Mathura', 26, 'UP', 0),
('Budaun', 26, 'UP', 0),
('Rampur', 26, 'UP', 0),
('Shahjahanpur', 26, 'UP', 0),
('Farrukhabad', 26, 'UP', 0),
('Maunath Bhanjan', 26, 'UP', 0),
('Hapur', 26, 'UP', 0),
('Ayodhya', 26, 'UP', 0),
('Etawah', 26, 'UP', 0),
('Mirzapur', 26, 'UP', 0),
('Bulandshahr', 26, 'UP', 0),
('Sambhal', 26, 'UP', 0),
('Amroha', 26, 'UP', 0),
('Hardoi', 26, 'UP', 0),
('Fatehpur', 26, 'UP', 0),
('Raebareli', 26, 'UP', 0),
('Orai', 26, 'UP', 0),
('Sitapur', 26, 'UP', 0),
('Bahraich', 26, 'UP', 0),
('Modinagar', 26, 'UP', 0),
('Unnao', 26, 'UP', 0),
('Jaunpur', 26, 'UP', 0),
('Lakhimpur', 26, 'UP', 0),
('Hathras', 26, 'UP', 0),
('Banda', 26, 'UP', 0),
('Pilibhit', 26, 'UP', 0),
('Barabanki', 26, 'UP', 0),
('Khurja', 26, 'UP', 0),
('Gonda', 26, 'UP', 0),
('Mainpuri', 26, 'UP', 0),
('Lalitpur', 26, 'UP', 0),
('Etah', 26, 'UP', 0),
('Deoria', 26, 'UP', 0),
('Ghazipur', 26, 'UP', 0),
('Greater Noida', 26, 'UP', 0),
('Rae Bareli', 26, 'UP', 0),

-- Uttarakhand
('Dehradun', 27, 'UK', 1),
('Haridwar', 27, 'UK', 1),
('Roorkee', 27, 'UK', 0),
('Haldwani', 27, 'UK', 0),
('Rudrapur', 27, 'UK', 0),
('Kashipur', 27, 'UK', 0),
('Rishikesh', 27, 'UK', 0),
('Ramnagar', 27, 'UK', 0),
('Pithoragarh', 27, 'UK', 0),
('Manglaur', 27, 'UK', 0),
('Nainital', 27, 'UK', 0),
('Mussoorie', 27, 'UK', 0),
('Tehri', 27, 'UK', 0),
('Pauri', 27, 'UK', 0),
('Nagla', 27, 'UK', 0),

-- West Bengal
('Kolkata', 28, 'WB', 1),
('Howrah', 28, 'WB', 1),
('Durgapur', 28, 'WB', 1),
('Asansol', 28, 'WB', 1),
('Siliguri', 28, 'WB', 1),
('Bardhaman', 28, 'WB', 0),
('Malda', 28, 'WB', 0),
('Baharampur', 28, 'WB', 0),
('Habra', 28, 'WB', 0),
('Kharagpur', 28, 'WB', 0),
('Shantipur', 28, 'WB', 0),
('Dankuni', 28, 'WB', 0),
('Dhulian', 28, 'WB', 0),
('Ranaghat', 28, 'WB', 0),
('Haldia', 28, 'WB', 0),
('Raiganj', 28, 'WB', 0),
('Krishnanagar', 28, 'WB', 0),
('Nabadwip', 28, 'WB', 0),
('Medinipur', 28, 'WB', 0),
('Jalpaiguri', 28, 'WB', 0),
('Balurghat', 28, 'WB', 0),
('Basirhat', 28, 'WB', 0),
('Bankura', 28, 'WB', 0),
('Chakdaha', 28, 'WB', 0),
('Darjeeling', 28, 'WB', 0),
('Alipurduar', 28, 'WB', 0),
('Purulia', 28, 'WB', 0),
('Jangipur', 28, 'WB', 0),

-- Delhi
('New Delhi', 32, 'DL', 1),
('Delhi', 32, 'DL', 1),
('Dwarka', 32, 'DL', 0),
('Rohini', 32, 'DL', 0),
('Saket', 32, 'DL', 0),
('Laxmi Nagar', 32, 'DL', 0),
('Karol Bagh', 32, 'DL', 0),
('Connaught Place', 32, 'DL', 0),
('Nehru Place', 32, 'DL', 0),
('Vasant Kunj', 32, 'DL', 0),

-- Chandigarh
('Chandigarh', 30, 'CH', 1),

-- Puducherry
('Puducherry', 36, 'PY', 1),
('Karaikal', 36, 'PY', 0),
('Yanam', 36, 'PY', 0),
('Mahe', 36, 'PY', 0);
